# Base Config

# site
# default "AcyOrt", "A Node.js blog tool powered by GitHub."
title: zWing
description: Just a blog.

gitToken: b#75128406f54c3653958e2d66befe6c5cf02ce7e

# rss
# set false if not need rss output
# default "rss.xml"
rss: true

# site url. you can set as 'http://yoursite.com/child' if necessary
# please add 'http://' or 'https://'
# default "https://acyortjs.github.io"
url: http://zWingz.github.io

# theme
# default "ccc45"
template: acyort-templates-donob-plus

# menu
menu:
  Archives: /archives/
  About: /about/

repository: zWingz/my-blog-config

pageSize:
  posts: 5

public: public

timezone: Asia/Shanghai
plugins:
  - acyort-plugin-fetch-issues
  - acyort-donob-renderer
  - acyort-plugin-rss
  
favicon: favicon.ico

gitalk:
  clientID: '0438ed96c0cb944693a7'
  clientSecret: '23e7aa3152f5d03d8f20029540741d6f886c9f5b'
