# 注意这个文件名为 config.yml，在 .circleci 目录下
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:latest

    working_directory: ~/acyort
    filters:
      branches:
        only:
          - master # 这个是配置文件的分支名，注意不要写错分支

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn deploy
      # - run: git reset --hard origin/master # 同上
      # - run: git add .
      - run: git config user.name "zWingz"
      - run: git config user.email "371657110@qq.com"
      # - run: git commit -m "Updated by circleci - `date`"
      - run: cp google1c8aa0f9ba6c9db0.html ./public/google1c8aa0f9ba6c9db0.html
      - run: cp CNAME ./public/CNAME
      - run: cp README.md ./public/README.md
      - run: npx gh-pages -d public -r https://${gh_token}@github.com/zWingz/zWingz.github.io.git -b master -m "Updated by circleci - `date`" # ${gh_token}
